### PR TITLE
Making the replay feature to work on iOS13

### PR DESCRIPTION
**Pull request by germanleiva**
Renamed the class ARReplaySensor to ARReplaySensorPublic, added a new method in ARReplaySensorDelegate (replaySensorDidFinishLoadingWithStartTimestamp:endTimestamp:), and use it in the MainViewController instead of replaySensorDidFinishLoadingFrames.

I briefly tested the replay feature and it works but it might be wise to check all the previous features in detail.

### CODE REVIEW

**Comment by AndrewHartAR** [comment]
I don't think you committed any code here, but just changed a file name?

**Comment by AndrewHartAR** [comment]
I've made the changes mentioned, and uploaded the zip [here](
https://github.com/ittybittyapps/ARRecorder/issues/5#issuecomment-542749931), however I'm having an issue with iOS 13 playback.

**Review by tonyarnold — CHANGES_REQUESTED** [review]
I'm keen to see a PR that fixes iOS 13 support for this project, however renaming a single file isn't going to do that. 

@germanleiva is there more to this work that wasn't committed?

**Comment by vlas-voloshin** [comment]
👉 #7

**Pull request closed without merging**
